import { gql } from "@apollo/client";

const LOAD_SCHOOLS = gql`
  query Schools {
    schools {
      id
      name
      emis_number
      upi_code
      ownership_type
      school_category
      year_established
      head_teacher_name
      head_teacher_contact
      location_type
      region
      district
      sub_county
      parish
      distance_from_achor_hq
      latitude
      longitude
      total_enrollment
      total_teachers
      male_teachers
      female_teachers
      num_of_staff
      signature_program
      has_electricity
      electricity_planned
      has_secure_room_for_ict
      has_computer_lab
      has_furniture
      computers
      tablets
      smartphones
      projectors
      interactive_whiteboards
      other_devices
      has_internet
      connection_types
      is_connection_stable
      internet_provider
      is_fenced
      has_security_guard
      has_theft_incidents
      theft_details
      has_toilets
      has_water_source
      within_30km_from_archor_school
      accessible_all_year
      is_inclusive
      serves_special_needs
      ict_trained_teachers
      digital_tool_usage
      has_digital_content
      content_source
      has_peer_support
      ongoing_capacity_building
      permanent_classrooms
      semi_permanent_classrooms
      temporary_classrooms
      pupil_classroom_ratio
      boys_toilets
      girls_toilets
      staff_toilets
      water_access
      security_infrastructure
      school_accessibility
      nearby_health_facility
      has_active_smc
      has_active_pta
      engagement_with_deo
      ngo_support
      community_contributions
      ple_pass_rate
      literacy_trends
      digital_content_users
      innovations
      assessor_notes
      assessed_by
    }
  }
`;

const LOAD_SCHOOL_DETAILS = gql`
query school($schoolId: ID!) {
  school(id: $schoolId) {
    id
    name
    emis_number
    upi_code
    ownership_type
    school_category
    year_established
    head_teacher_name
    head_teacher_contact
    district
    region
    sub_county
    parish
    distance_from_achor_hq
    latitude
    longitude
    total_enrollment
    total_teachers
    male_teachers
    female_teachers
    num_of_staff
    signature_program
    has_electricity
    electricity_planned
    has_secure_room_for_ict
    has_computer_lab
    has_furniture
    computers
    tablets
    smartphones
    projectors
    interactive_whiteboards
    other_devices
    has_internet
    connection_types
    is_connection_stable
    internet_provider
    is_fenced
    has_security_guard
    has_theft_incidents
    theft_details
    has_toilets
    has_water_source
    within_30km_from_archor_school
    accessible_all_year
    is_inclusive
    serves_special_needs
    ict_trained_teachers
    digital_tool_usage
    has_digital_content
    content_source
    has_peer_support
    ongoing_capacity_building
    location_type
    permanent_classrooms
    semi_permanent_classrooms
    temporary_classrooms
    pupil_classroom_ratio
    boys_toilets
    girls_toilets
    staff_toilets
    water_access
    security_infrastructure
    school_accessibility
    nearby_health_facility
    has_active_smc
    has_active_pta
    engagement_with_deo
    ngo_support
    community_contributions
    ple_pass_rate
    literacy_trends
    digital_content_users
    innovations
    assessor_notes
    assessed_by
  }
}
`
const LOAD_SCHOOL_PERIODIC_OBSERVATIONS = gql`
query School_periodic_observations {
  school_periodic_observations {
    id
    school_id
    observation_date
    term_quarter
    p6_registered
    p6_present
    p6_notes
    p7_registered
    p7_present
    p7_notes
    teacher_attendance_total
    teacher_attendance_present
    teacher_attendance_absent
    dropouts_total
    dropouts_male
    dropouts_female
    dropouts_reasons
    digital_subjects
    lesson_frequency
    teachers_using_digital
    good_lesson_observed
    peer_support
    learners_engaged
    learners_using_devices
    engagement_level
    # challenges
    laptops_total
    laptops_working
    laptops_not_working
    laptops_notes
    projectors_total
    projectors_working
    projectors_not_working
    projectors_notes
    routers_total
    routers_working
    routers_not_working
    routers_notes
    solar_total
    solar_working
    solar_not_working
    solar_notes
    device_storage
    sign_in_register
    # power_available
    internet_status
    content_sources
    new_content_introduced
    learner_access_levels
    head_teacher_involved
    ict_coordinator
    ict_schedule
    smc_meeting
    ict_discussions
    # community_engagement
    achievements
    infrastructure_challenges
    training_challenges
    connectivity_challenges
    content_challenges
    other_challenges
    immediate_actions
    capacity_building_needs
    support_requests
    learner_attendance
    teacher_attendance
    digital_tools_use
    infrastructure_condition
    internet_availability
    management_support
    next_visit
    assessor_notes
    assessed_by
    created_at
    updated_at
  }
}
`

export { LOAD_SCHOOLS, LOAD_SCHOOL_DETAILS, LOAD_SCHOOL_PERIODIC_OBSERVATIONS };
