import { gql } from "@apollo/client";

const LOAD_SCHOOLS = gql`
  query Schools {
    schools {
      id
      name
      emis_number
      upi_code
      region
      district
      sub_county
      latitude
      longitude
      type
      environment
      ownership_type
      school_category
      signature_program
      year_established
      head_teacher
      school_email
      school_phone
      total_students
      male_students
      female_students
      student_computers
      teacher_computers
      projectors
      smart_boards
      tablets
      laptops
      has_computer_lab
      lab_condition
      has_ict_room
      has_electricity
      has_secure_room
      has_furniture
      power_backup
      connection_type
      bandwidth_mbps
      wifi_coverage
      stability
      has_usage_policy
      provider
      is_stable
      has_lms
      lms_name
      has_licensed_software
      licensed_software
      has_productivity_suite
      productivity_suite
      has_digital_library
      has_local_content
      content_source
      ict_trained_teachers
      total_teachers
      male_teachers
      female_teachers
      p5_to_p7_teachers
      support_staff
      monthly_trainings
      teacher_competency_level
      has_capacity_building
      ict_integrated_lessons
      uses_ict_assessments
      has_student_projects
      uses_blended_learning
      has_assistive_tech
      digital_tool_usage_frequency
      has_digital_content
      has_peer_support
      has_ict_policy
      aligned_with_national_strategy
      has_ict_committee
      has_ict_budget
      has_monitoring_system
      has_active_smc
      has_active_pta
      has_local_leader_engagement
      digital_literacy_level
      has_ict_club
      uses_online_platforms
      student_feedback_rating
      students_using_digital_content
      has_parent_portal
      has_community_outreach
      has_industry_partners
      partner_organizations
      ngo_support
      community_contributions
      is_fenced
      has_security_guard
      has_recent_incidents
      incident_details
      has_toilets
      has_water_source
      distance_from_hq
      is_accessible_all_year
      is_inclusive
      serves_girls
      serves_pwds
      serves_refugees
      is_only_school_in_area
      permanent_classrooms
      semi_permanent_classrooms
      temporary_classrooms
      pupil_classroom_ratio
      boys_toilets
      girls_toilets
      staff_toilets
      water_access
      security_infrastructure
      school_accessibility
      nearby_health_facility
      health_facility_distance
      ple_pass_rate_year1
      ple_pass_rate_year2
      ple_pass_rate_year3
      literacy_trends
      numeracy_trends
      innovations
      unique_achievements
      periodic_observations {
        id
        school_id
        date
        period
        infrastructure {
          computers
          tablets
          projectors
          printers
          internet_connection
          internet_speed_mbps
          power_source
          power_backup
          functional_devices
        }
        usage {
          teachers_using_ict
          total_teachers
          weekly_computer_lab_hours
          student_digital_literacy_rate
        }
        software {
          operating_systems
          educational_software
          office_applications
        }
        capacity {
          ict_trained_teachers
          support_staff
        }
      }
    }
  }
`;

const LOAD_SCHOOL_DETAILS = gql`
  query School($schoolId: ID!) {
    school(id: $schoolId) {
      id
      name
      emis_number
      upi_code
      region
      district
      sub_county
      latitude
      longitude
      type
      environment
      ownership_type
      school_category
      signature_program
      year_established
      head_teacher
      school_email
      school_phone
      total_students
      male_students
      female_students
      student_computers
      teacher_computers
      projectors
      smart_boards
      tablets
      laptops
      has_computer_lab
      lab_condition
      has_ict_room
      has_electricity
      has_secure_room
      has_furniture
      power_backup
      connection_type
      bandwidth_mbps
      wifi_coverage
      stability
      has_usage_policy
      provider
      is_stable
      has_lms
      lms_name
      has_licensed_software
      licensed_software
      has_productivity_suite
      productivity_suite
      has_digital_library
      has_local_content
      content_source
      ict_trained_teachers
      total_teachers
      male_teachers
      female_teachers
      p5_to_p7_teachers
      support_staff
      monthly_trainings
      teacher_competency_level
      has_capacity_building
      ict_integrated_lessons
      uses_ict_assessments
      has_student_projects
      uses_blended_learning
      has_assistive_tech
      digital_tool_usage_frequency
      has_digital_content
      has_peer_support
      has_ict_policy
      aligned_with_national_strategy
      has_ict_committee
      has_ict_budget
      has_monitoring_system
      has_active_smc
      has_active_pta
      has_local_leader_engagement
      digital_literacy_level
      has_ict_club
      uses_online_platforms
      student_feedback_rating
      students_using_digital_content
      has_parent_portal
      has_community_outreach
      has_industry_partners
      partner_organizations
      ngo_support
      community_contributions
      is_fenced
      has_security_guard
      has_recent_incidents
      incident_details
      has_toilets
      has_water_source
      distance_from_hq
      is_accessible_all_year
      is_inclusive
      serves_girls
      serves_pwds
      serves_refugees
      is_only_school_in_area
      permanent_classrooms
      semi_permanent_classrooms
      temporary_classrooms
      pupil_classroom_ratio
      boys_toilets
      girls_toilets
      staff_toilets
      water_access
      security_infrastructure
      school_accessibility
      nearby_health_facility
      health_facility_distance
      ple_pass_rate_year1
      ple_pass_rate_year2
      ple_pass_rate_year3
      literacy_trends
      numeracy_trends
      innovations
      unique_achievements
      periodic_observations {
        id
        school_id
        date
        period
        infrastructure {
          computers
          tablets
          projectors
          printers
          internet_connection
          internet_speed_mbps
          power_source
          power_backup
          functional_devices
        }
        usage {
          teachers_using_ict
          total_teachers
          weekly_computer_lab_hours
          student_digital_literacy_rate
        }
        software {
          operating_systems
          educational_software
          office_applications
        }
        capacity {
          ict_trained_teachers
          support_staff
        }
      }
    }
  }
`;
const LOAD_SCHOOL_PERIODIC_OBSERVATIONS = gql`
 query School_periodic_observations {
  school_periodic_observations {
    id
    school_id
    date
    period
    infrastructure {
      computers
      tablets
      projectors
      printers
      internet_connection
      internet_speed_mbps
      power_source
      power_backup
      functional_devices
    }
    usage {
      teachers_using_ict
      total_teachers
      weekly_computer_lab_hours
      student_digital_literacy_rate
    }
    software {
      operating_systems
      educational_software
      office_applications
    }
    capacity {
      ict_trained_teachers
      support_staff
    }
  }
}
`;

export { LOAD_SCHOOLS, LOAD_SCHOOL_DETAILS, LOAD_SCHOOL_PERIODIC_OBSERVATIONS };
